Add tenant organizations
eduNEXT/eox-tenant pull request #103
Opened 2020-09-22 21:55 UTC by andrey-canon

## Description
- Remove django_mysql jsonfields and use an alternative model called TenantOrganization
- Add synchronization command 
- Add receiver method to create organizations

2020-09-22 23:10 UTC, mariajgrimaldi approved these changes

2020-09-23 22:16 UTC, felipemontoya requested changes
Im wondering some things:

- should we add a data migration for the first sync?
- should we make it fail less fatally if the migrations have not been run?

Also:
- could you please add a note in the readme about the synchronize_organizations command?
- about the admin page for the orgs:
  - could you add a text filter? both on the name of the org, and the routes/microsites domains or keys
  - can you make the list of the orgs display the tenants/microsites where it is linked?
  - on the admin page, make it only display the string of the org, not the __repr__

2020-09-23 22:16 UTC, felipemontoya commented on eox_tenant/management/commands/synchronize_organizations.py
> +                sleep(1)
Can we make this value an override with default 0.2 seconds?

2020-09-23 22:16 UTC, felipemontoya commented on eox_tenant/models.py
> +        return "<Tenant organization: {}>".format(self.name)
For readability can we make this shorter? <Org: {}> ?

2020-09-23 22:16 UTC, felipemontoya commented on eox_tenant/utils.py
> +def synchronize_tenant_organizations(instance):
So far this method only adds new orgs, do we have anything to remove old orgs and purge them?

2020-09-23 22:16 UTC, felipemontoya commented on eox_tenant/models.py
> +    values = JSONField(blank=True, default={}, load_kwargs={'object_pairs_hook': collections.OrderedDict})
Does this change in any way imply that we need to change the data in the database?

2020-09-25 21:31 UTC, merged